/**
 * Auto Generated by LibragonExporter for TexturePacker
 **/

#include <libdragon.h>
#include <malloc.h>

typedef enum _interface_sprites { 
    SPRITE_buttonA,
    SPRITE_buttonL,
    SPRITE_buttonR,
    SPRITE_buttonStart,
    SPRITE_dpad,
    SPRITE_joystick,
    SPRITE_record,
    SPRITE_interface_SPRITES_MAX
} interface_sprites;

#define alloc_and_load_spritesheet_interface(sprite)\
{\
    int fp = dfs_open("/interface.sprite");\
    sprite = (sprite_t*)malloc(dfs_size(fp));\
    dfs_read(sprite, 1, dfs_size(fp), fp);\
    dfs_close(fp);\
}
