/**
 * Auto Generated by LibragonExporter for TexturePacker
 **/

#include <libdragon.h>
#include <malloc.h>

typedef enum _thumbs_sprites { 
    SPRITE_flying_bats_small,
    SPRITE_jump_rope_small,
    SPRITE_thumbs_SPRITES_MAX
} thumbs_sprites;

#define alloc_and_load_spritesheet_thumbs(sprite)\
{\
    int fp = dfs_open("/thumbs.sprite");\
    sprite = (sprite_t*)malloc(dfs_size(fp));\
    dfs_read(sprite, 1, dfs_size(fp), fp);\
    dfs_close(fp);\
}
