/**
 * Auto Generated by LibragonExporter for TexturePacker
 **/

#include <libdragon.h>
#include <malloc.h>

typedef enum _minigame_detail_sprites { 
    SPRITE_player_1_disconnected,
    SPRITE_player_1_not_ready,
    SPRITE_player_1_ready,
    SPRITE_player_2_disconnected,
    SPRITE_player_2_not_ready,
    SPRITE_player_2_ready,
    SPRITE_player_3_disconnected,
    SPRITE_player_3_not_ready,
    SPRITE_player_3_ready,
    SPRITE_player_4_disconnected,
    SPRITE_player_4_not_ready,
    SPRITE_player_4_ready,
    SPRITE_minigame_detail_SPRITES_MAX
} minigame_detail_sprites;

#define alloc_and_load_spritesheet_minigame_detail(sprite)\
{\
    int fp = dfs_open("/minigame_detail.sprite");\
    sprite = (sprite_t*)malloc(dfs_size(fp));\
    dfs_read(sprite, 1, dfs_size(fp), fp);\
    dfs_close(fp);\
}
