/**
 * Auto Generated by LibragonExporter for TexturePacker
 **/

#include <libdragon.h>
#include <malloc.h>

typedef enum _flying_bat_sprites { 
    SPRITE_fb_bat_1,
    SPRITE_fb_bat_2,
    SPRITE_fb_bat_3,
    SPRITE_fb_bat_4,
    SPRITE_fb_obstacle_1,
    SPRITE_fb_obstacle_2,
    SPRITE_fb_sky,
    SPRITE_flying_bat_SPRITES_MAX
} flying_bat_sprites;

#define alloc_and_load_spritesheet_flying_bat(sprite)\
{\
    int fp = dfs_open("/flying_bat.sprite");\
    sprite = (sprite_t*)malloc(dfs_size(fp));\
    dfs_read(sprite, 1, dfs_size(fp), fp);\
    dfs_close(fp);\
}
